"""inclusao de campo respondido

Revision ID: 023b2c68b8a9
Revises: 096b47a2b992
Create Date: 2025-04-13 12:26:10.141204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023b2c68b8a9'
down_revision = '096b47a2b992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.add_column(sa.Column('respondido', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_column('respondido')

    # ### end Alembic commands ###
